version: 1.0.{build}

image:
  - Visual Studio 2017

environment:
  matrix:
  - QTDIR: C:\Qt\5.12.2\msvc2017_64

install:
  - set PATH=%QTDIR%\bin;%PATH%

configuration:
- Release

before_build:
  - cmake -H. -Bbuild -G "Visual Studio 15 2017 Win64" -DSARA_BUILD_VIDEOIO=ON -DSARA_BUILD_TESTS=ON -DSARA_BUILD_SAMPLES=ON -DBOOST_ROOT="C:\Libraries\boost_1_63_0"

build_script:
  - '"C:\Program Files (x86)\MSBuild\15.0\Bin\MSBuild.exe" build\Sara.sln /m /verbosity:minimal'
