version: 1.0.{build}

image:
  - Visual Studio 2017

cache: c:\tools\vcpkg\installed

clone_folder: c:\projects\sara

environment:
  # These environment variables will be picked up in CMake.
  VCPKG_TOOLCHAIN_FILE: C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake
  QTDIR: C:/Qt/5.13.2/msvc2017_64
  BOOST_ROOT: C:/Libraries/boost_1_69_0
  matrix:
    - generator: "Visual Studio 15 2017 Win64"

install:
  # Set up Qt5.
  - set PATH=%QTDIR%\bin;%PATH%

  # Update vcpkg.
  - cd c:\tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat

  # Install Image I/O libraries. (less than 5 minutes to build)
  - vcpkg install libjpeg-turbo:x64-windows
  - vcpkg install libpng:x64-windows
  - vcpkg install tiff:x64-windows

  # # Install Video I/O libraries. (25 minutes to build)
  # - vcpkg install ffmpeg:x64-windows

  # Install HDF5 libraries. (4 minutes to build).
  - vcpkg install hdf5[cpp]:x64-windows

  # # Install Ceres libraries. (23 minutes to build)
  # - vcpkg install ceres:x64-windows

  # Integrate vcpkg with msbuild.
  - cd c:\tools\vcpkg
  - vcpkg integrate install

configuration:
  # - Debug
  - Release

before_build:
  # Go back the repository folder so that we can run CMake.
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmake -H. -B../sara-build -G "%generator%" -DCMAKE_TOOLCHAIN_FILE:FILEPATH=%VCPKG_TOOLCHAIN_FILE% -DSARA_BUILD_SHARED_LIBS=ON -DSARA_BUILD_VIDEOIO:BOOL=OFF -DSARA_BUILD_TESTS:BOOL=ON -DSARA_BUILD_SAMPLES:BOOL=ON -DCMAKE_PREFIX_PATH="%QTDIR%" -DBOOST_ROOT=%BOOST_ROOT%

build:
  project: c:\projects\sara-build\Sara.sln
  parallel: true
  verbosity: minimal
