image: nvidia/cudagl:10.1-runtime-ubuntu18.04


before_script:
  - apt-get update -qq
  - apt-get install -y
      # GNU C++ toolchain
      build-essential
      cmake
      doxygen
      git
      # Boost
      libboost-all-dev
      # HDF5
      libhdf5-dev
      # Image I/O
      libjpeg-dev
      libpng-dev
      libtiff5-dev
      # FFMPEG Video I/O
      libavcodec-dev
      libavformat-dev
      libavutil-dev
      # OpenGL
      libglew-dev
      libglfw3-dev
      # OpenCL
      ocl-icd-opencl-dev
      opencl-headers
      # Ceres solver
      libceres-dev
      # Qt
      qtbase5-dev
      qt3d5-dev
      qt3d-assimpsceneimport-plugin
      qt3d-defaultgeometryloader-plugin
      qt3d-gltfsceneio-plugin
      qt3d-scene2d-plugin
  - apt-get install -qq
      libboost-python-dev
      python3-dev
  - apt-get install -y xvfb
  - Xvfb :1 -noreset 1>/dev/null 2>&1 &
  - export DISPLAY=:1

job:
  script:
    - mkdir build
    - cd build
    - cmake ..
        -DCMAKE_BUILD_TYPE:STRING=Debug
        -DSARA_BUILD_SHARED_LIBS:BOOL=ON
        -DSARA_BUILD_SAMPLES:BOOL=ON
        -DSARA_BUILD_TESTS:BOOL=ON
    - make  -j$(nproc)
    - DISPLAY=:1 ctest --output-on-failure --exclude-regex "test_graphics_*|test_core_ipc_cond1"
    - make package
