image: nvidia/cudagl:10.1-runtime-ubuntu18.04


before_script:
  - apt-get update -qq
  - apt-get install -y
      build-essential
      cmake
      doxygen
      git
      libboost-all-dev
      libhdf5-dev
      libjpeg-dev
      libpng-dev
      libtiff5-dev
      libavcodec-dev
      libavformat-dev
      libavutil-dev
      qtbase5-dev
  - apt-get install -qq
      libboost-python-dev
      python3-dev
  - apt-get install -y xvfb
  - Xvfb :1 -noreset 1>/dev/null 2>&1 &
  - export DISPLAY=:1

job:
  script:
    - mkdir build
    - cd build
    - cmake ..
        -DCMAKE_BUILD_TYPE:STRING=Debug
        -DSARA_BUILD_SHARED_LIBS:BOOL=ON
        -DSARA_BUILD_SAMPLES:BOOL=ON
        -DSARA_BUILD_TESTS:BOOL=ON
    - make  -j$(nproc)
    - DISPLAY=:1 ctest --output-on-failure --exclude-regex "test_graphics_*|test_core_ipc_cond1"
    - make package
