image: ubuntu:16.04


before_script:
  - apt-get update -qq
  - apt-get install -y
       cmake
       doxygen
       libjpeg8-dev
       libpng12-dev
       libtiff5-dev
       libavcodec-dev
       libavformat-dev
       libavutil-dev
       qtbase5-dev
  - apt-get install -qq
       libboost-python-dev
       python3-dev

job:
  script:
    - mkdir build
    - cd build
    - cmake ..
       -DCMAKE_BUILD_TYPE=Debug
       -DSARA_BUILD_SHARED_LIBS=ON
       -DSARA_BUILD_SAMPLES=ON
       -DSARA_BUILD_TESTS=ON
    - make  -j$(nproc)
    - ctest --output-on-failure
    - make package
