language: cpp

sudo: required
dist: bionic
services:
  - xvfb

cache:
  bundler: true

addons:
  apt:
    packages:
      - build-essential
      - cmake
      - doxygen
      - git
      - libboost-all-dev
      - libhdf5-dev
      - libjpeg-dev
      - libpng-dev
      - libtiff5-dev
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libglew-dev
      - libglfw3-dev
      - ocl-icd-opencl-dev
      - opencl-headers
      - libpocl-dev
      - libceres-dev
      - python3-dev
      - qtbase5-dev
      - qt3d5-dev
      - qt3d-assimpsceneimport-plugin
      - qt3d-defaultgeometryloader-plugin
      - qt3d-gltfsceneio-plugin
      - qt3d-scene2d-plugin

compiler:
  - gcc

install:
  - bundle install

script:
  # Build libraries.
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DSARA_BUILD_TESTS=ON -DSARA_BUILD_SAMPLES=ON -DSARA_BUILD_VIDEOIO=ON -DSARA_FFMPEG_DIR=$HOME/ffmpeg ..
  - make -j$(nproc)
  # Run tests.
  - ctest --output-on-failure
  # Make package.
  - make package

after_success:
  - cd ..
  - lcov --compat-libtool --directory build --base-directory=cpp/src --capture --output-file=coverage.info
  - lcov --remove coverage.info 'usr/*' --output-file coverage.info
  - lcov --remove coverage.info 'cpp/third-party/*' --output-file coverage.info
  - lcov --remove coverage.info 'cpp/test/*' --output-file coverage.info
  - lcov --remove coverage.info 'build/moc_*' --output-file coverage.info
  - coveralls-lcov coverage.info
