language: cpp

sudo: required
dist: xenial
services:
  - xvfb

cache:
  bundler: true
  directories:
  - $HOME/ffmpeg

addons:
  apt:
    sources:
    - ubuntu-sdk-team
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
    - qtbase5-dev
    - lcov
    - libboost-all-dev
    - libhdf5-dev
    - libqt5opengl5
    - libqt5opengl5-dev
    - yasm

# compiler:
#   - gcc

env:
  - CC=gcc-7 CXX=g++-7

install:
  # Build and install third-party locally.
  - ./scripts/travis-build-and-install-ffmpeg.sh
  - bundle install

script:
  # Build libraries.
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DSARA_BUILD_TESTS=ON -DSARA_BUILD_SAMPLES=ON -DSARA_BUILD_VIDEOIO=ON -DSARA_FFMPEG_DIR=$HOME/ffmpeg ..
  - make -j$(nproc)
  # Run tests.
  - xvfb-run ctest --output-on-failure
  # Make package.
  - make package

after_success:
  - cd ..
  - lcov --compat-libtool --directory build --base-directory=cpp/src --capture --output-file=coverage.info
  - lcov --remove coverage.info 'usr/*' --output-file coverage.info
  - lcov --remove coverage.info 'cpp/third-party/*' --output-file coverage.info
  - lcov --remove coverage.info 'cpp/test/*' --output-file coverage.info
  - lcov --remove coverage.info 'build/moc_*' --output-file coverage.info
  - coveralls-lcov coverage.info
