language: cpp

sudo: false

cache:
  apt: true
  directories:
  - $HOME/ffmpeg
  - $HOME/lcov

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - ubuntu-sdk-team
    packages:
    - rpm
    - gcc-4.9
    - g++-4.9
    - gcov-4.9
    - qtbase5-dev
    - yasm

compiler:
  - gcc

before_script:
  # Specify the GCC version we want to use.
  - export CC=/usr/bin/gcc-4.9
  - export CXX=/usr/bin/g++-4.9
  # Build third
  - ./scripts/travis-build-and-install-third-party.sh
  # Fake X server
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  # Build libraries.
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DSARA_BUILD_TESTS=ON -DSARA_BUILD_SAMPLES=ON ..
  - make -j4
  # Run tests.
  - ctest --output-on-failure
  # Make package.
  - make package

after_success:
  - cd ..
  - lcov --gcov-tool=/usr/bin/gcov-4.9 --compat-libtool --directory build --base-directory=src --capture --output-file=coverage.info
  - lcov --remove coverage.info 'usr/*' --output-file coverage.info
  - lcov --remove coverage.info 'third-party/*' --output-file coverage.info
  - lcov --remove coverage.info 'test/*' --output-file coverage.info
  - lcov --remove coverage.info 'build/moc_*' --output-file coverage.info
  - coveralls-lcov coverage.info
