language: cpp

compiler:
  #- clang
  - gcc

before_install:
  # Update apt repositories to get Qt5.
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq

install:
  # Install Qt5
  - sudo apt-get install -qq qtbase5-dev

before_script:
  # Fake X server
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j 4
  - make verbose_test
