language: cpp

compiler:
  #- clang
  - gcc

before_install:
  # Update apt repositories to get Qt5.
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq

install:
  # Install Qt5
  - sudo apt-get install -qq qtbase5-dev
  # Install lcov for code coverage.
  - sudo apt-get install lcov
  # Install coveralls-lcov for code coverage.
  - gem install coveralls-lcov

before_script:
  # Fake X server
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j 4
  - make verbose_test

after_success:
  - cd ..
  - lcov --compat-libtool --directory build --base-directory=src --capture --output-file=coverage.info
  - lcov --remove coverage.info 'usr/*' --output-file coverage.info
  - lcov --remove coverage.info 'third-party/*' --output-file coverage.info
  - lcov --remove coverage.info 'test/*' --output-file coverage.info
  - lcov --remove coverage.info 'build/moc_*' --output-file coverage.info
  - coveralls-lcov coverage.info
