language: cpp

compiler:
  #- clang
  - gcc

before_install:
  # Update apt repositories to get GNU compiler 4.8.
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  # Update apt repositories to get Qt5.
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq

install:
  # Install GCC 4.8 for C++11 features.
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  # Install Qt5.
  - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  # Install lcov.
  - sudo apt-get install lcov
  # Install coveralls-lcov for code coverage.
  - gem install coveralls-lcov

before_script:
  # Fake X server.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Create build directory.
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..

script:
  - make -j 4
  - make verbose_test

after_success:
  - cd ..
  - lcov --directory build --base-directory=src --no-external --capture --output-file=coverage.info
  - lcov --remove coverage.info 'third-party/*' --output-file coverage.info
  - lcov --remove coverage.info 'test/*' --output-file coverage.info
  - lcov --remove coverage.info '*/build/*' --output-file coverage.info
  - coveralls-lcov coverage.info
