version: 1.0.{build}

os: unstable

environment:
  matrix:
  - VS_VERSION: 12
    VS_PLATFORM: win32
    QT5_DIR: C:\Qt\5.4\msvc2013_32_opengl
  - VS_VERSION: 12
    VS_PLATFORM: x64
    QT5_DIR: C:\Qt\5.4\msvc2013_64_opengl

install:
  - set PATH=%PATH%;%QT5_DIR%\bin

configuration:
- Debug
- Release

before_build:
- echo %VS_VERSION%
- echo %PATH%
- echo %QT5_DIR%
- dir C:\Qt\5.4\msvc2013_32_opengl
- cmake -H. -Bbuild -G "Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM%

build:
  project: build\DO-CV.sln
  parallel: true
  verbosity: detailed

test_script:
- cd build && ctest --verbose --build-config %CONFIGURATION%
