version: 1.0.{build}

os: unstable

environment:
  matrix:
  - VS_VERSION: 15
    VS_PLATFORM: x64
    QTDIR: C:\Qt\5.7\msvc2015_64

install:
  - set PATH=%QTDIR%\bin;%PATH%

configuration:
- Release

before_build:
  - cmake -H. -Bbuild -G "Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM% -DSARA_BUILD_VIDEOIO=ON -DSARA_BUILD_TESTS=ON -DSARA_BUILD_SAMPLES=ON

build_script:
  - '"C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe" build\Sara.sln /m /verbosity:minimal'
