version: 1.0.{build}

os: unstable

environment:
  matrix:
  - VS_VERSION: 12
    VS_PLATFORM: x64
    QTDIR: C:\Qt\5.4\msvc2013_64_opengl

install:
  - set PATH=%QTDIR%\bin;%PATH%

configuration:
- Release

before_build:
- cmake -H. -Bbuild -G "Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM%

build:
  parallel: true
  project: build\DO-CV.sln
  verbosity: minimal
